### ISSUE TITLE
i cant redirect with "/"

### ISSUE THREAD

**Issue by eltrevii** [pndurette/gh-pages-url-shortener-action#5]
so i wanted to redirect to a page and i prefer using "/" as its better and shorter than putting the full url, so i put this:
![image](https://github.com/pndurette/gh-pages-url-shortener-action/assets/59333567/1006152c-bafa-4f2a-a3ad-a942391e9b7a)
but when you visit it it just says "/megathread"

**Comment by pndurette** [comment]
Hi @eltrevii! Yes that's by design, if you want `default_redirect` to send you somewhere else (instead of just showing text), it needs to be a full URL, so starting with `http` (or `https`).

**Comment by eltrevii** [comment]
sad
also, as i mentioned in #4, i think you should clarify how to use inputs in workflows on the readme

**Comment by eltrevii** [comment]
sad

**Comment by eltrevii** [comment]
i prefer with / because it could break if i change the domain or if its downloaded locally so yeah ig i should make my own? ill see if i can do that

**Comment by pndurette** [comment]
Can you give me more context on what you're trying to do?
All this does is a client-side HTTP redirect, so it needs to know the host!

Personally, I use it with its own sub-domain which only does link shortening.

**Comment by pndurette** [comment]
I just saw how you used it. I think it would work if you simply use the entire domain, i.e.:
```yaml
with:
  default_redirect: https://eltrevii.github.io/megathread/
```

**Comment by pndurette** [comment]
I've been thinking about this, and there's actually possibly a way to make your configuration work, actually. I need to look at it.

**Comment by eltrevii** [comment]
i use / because i might change domains, and im currently using pages.dev (cloudflare pages) so if i change the domain e.g. to github pages i wont have to change all the redirects

**Comment by eltrevii** [comment]
hey @pndurette, i was thinking... could you add another input for / redirects? you dont know how much i need this

**Comment by eltrevii** [comment]
hello?

**Comment by eltrevii** [comment]
@pndurette are you there???

**Comment by pndurette** [comment]
I was very busy, don’t be rude! But I implemented it anyway, `v2` was released and it added that. It’ll work exactly like your original example.

**Comment by eltrevii** [comment]
tysm
